#!/bin/sh

# Get the current working directory
PWD="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"

# Check if the script is run with at least one argument
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <action> <args>" >&2
  exit 1
fi

# Copy env.example or .env.example to .env if .env does not exist
if [ ! -f "$PWD/.env" ]; then
    if [ -f "$PWD/env.example" ]; then
        cp "$PWD/env.example" "$PWD/.env"
    elif [ -f "$PWD/.env.example" ]; then
        cp "$PWD/.env.example" "$PWD/.env"
    fi
fi

# Load the .env file if it exists
[ -f "$PWD/.env" ] && . "$PWD/.env"

# Set the name and default exec command
NAME=${POD_NAME:-$(basename "$PWD")}
EXEC="sh"

# Check if Docker is running
while ! docker info >/dev/null 2>&1; do
    echo "Docker does not seem to be running, sleep 2.."
    sleep 2
done

# Action functions
action_rm() {
    docker compose down
}

action_exec() {
    [ -n "$1" ] && EXEC="$1"
    docker exec -ti "$NAME" "$EXEC"
}

action_run() {
    docker compose down
    docker compose up -d
}

# Set the default action to "build" if none is provided
action=$1
shift

# Function to check if a function exists
function_exists() {
    type "$1" >/dev/null 2>&1
}

# Call the action function if it exists, otherwise show an error
if function_exists "action_$action"; then
    "action_$action" "$@"
else
    echo "Error: Unknown action: '$action'"
    echo "Usage: $0 <action> <args>"
    exit 1
fi
